//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolvesServer.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DoiTien
    {
   
        public int Id { get; set; }
        [DisplayName("Số lượng")]
        public Nullable<int> Quantity { get; set; }
        [DisplayName("ID Tài khoản")]
        public Nullable<int> IdAccount { get; set; }
        [DisplayName("STK")]
        public string STK { get; set; }
        [DisplayName("Ngân hàng")]
        public string Bank { get; set; }
        [DisplayName("Tên chủ tài khoản")]
        public string NameBank { get; set; }
        [DisplayName("Trạng thái")]
        public Nullable<bool> Status { get; set; }
    }
}
