//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolvesServer.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DoiTac
    {
        public int Id { get; set; }
        [DisplayName("Tên đối tác")]
        public string TenDoiTac { get; set; }
        [DisplayName("Trang web")]
        public string TrangWeb { get; set; }
        [DisplayName("Thông tin khác")]
        public string ThongTinKhac { get; set; }
    }
}
