//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolvesServer.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class Gold
    {
        public int Id { get; set; }
        [DisplayName("Tiêu đề")]
        public string Symbol { get; set; }
 
        public Nullable<double> SoldOut { get; set; }
        public Nullable<double> BuyInto { get; set; }
        [DisplayName("Ngày")]
        public Nullable<System.DateTime> Date { get; set; }
        [AllowHtml]
        [DisplayName("Nội dung")]
        public string Content { get; set; }
    }
}
