//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolvesServer.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class LoadWolf
    {
        public int Id { get; set; }
        [DisplayName("Wol")]
        public int Wolves { get; set; }
        [DisplayName("ID Tài khoản")]
        public int IdAccount { get; set; }
        [DisplayName("Trạng thái")]
        public Nullable<int> Status { get; set; }
        [DisplayName("Tài khoản")]

        public virtual Account Account { get; set; }
    }
}
