//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolvesServer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackVIP
    {
        public int Id { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Wol { get; set; }
    }
}
