//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolvesServer.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class SanGiaoDich
    {
        public int Id { get; set; }
        [DisplayName("Tiêu đề")]
        public string Titile { get; set; }
        [AllowHtml]
        [DisplayName("Nội dung")]
        public string Content { get; set; }
    }
}
