//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolvesServer.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TinHieuPost
    {
        public int Id { get; set; }
        [DisplayName("Ngày")]
        public Nullable<System.DateTime> Date { get; set; }
        [DisplayName("Nội dung")]
        public string Content { get; set; }
      
        public Nullable<double> TP { get; set; }
    
        public Nullable<double> SL { get; set; }
        [DisplayName("Hình ảnh")]
        public string Image { get; set; }
    }
}
